# Generated by Django 4.2 on 2026-01-27 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enterprise',
            old_name='registre_commerce_pdf',
            new_name='registre_commerce',
        ),
    ]
